// <auto-generated />
using System;
using Devpull.DbModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Devpull.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241113072534_CreateDb")]
    partial class CreateDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Devpull.DbModels.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("course_pk");

                    b.ToTable("course", (string)null);
                });

            modelBuilder.Entity("Devpull.DbModels.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("StepId")
                        .HasColumnType("uuid")
                        .HasColumnName("step_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("lesson_pk");

                    b.HasIndex("StepId");

                    b.ToTable("lesson", (string)null);
                });

            modelBuilder.Entity("Devpull.DbModels.Step", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("short_description");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("step_pk");

                    b.HasIndex("CourseId");

                    b.ToTable("step", (string)null);
                });

            modelBuilder.Entity("Devpull.DbModels.Lesson", b =>
                {
                    b.HasOne("Devpull.DbModels.Step", "Step")
                        .WithMany("Lessons")
                        .HasForeignKey("StepId")
                        .IsRequired()
                        .HasConstraintName("lesson_step_id_fk");

                    b.Navigation("Step");
                });

            modelBuilder.Entity("Devpull.DbModels.Step", b =>
                {
                    b.HasOne("Devpull.DbModels.Course", "Course")
                        .WithMany("Steps")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("step_course_id_fk");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Devpull.DbModels.Course", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("Devpull.DbModels.Step", b =>
                {
                    b.Navigation("Lessons");
                });
#pragma warning restore 612, 618
        }
    }
}
